-- AlterTable
ALTER TABLE "LaborCost" ALTER COLUMN "cost" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "OtherExpense" ALTER COLUMN "cost" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "ReusableLineItem" ALTER COLUMN "caseCost" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "SingleUseLineItem" ALTER COLUMN "caseCost" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "newCaseCost" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "WasteHaulingCost" ALTER COLUMN "monthlyCost" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "newMonthlyCost" SET DATA TYPE DOUBLE PRECISION;
